import { z } from "zod";
import OpenAI from "openai";
import {
  buildPrompt,
  TITLE_PROMPT_INSTRUCTIONS,
  DESCRIPTION_PROMPT_INSTRUCTIONS,
  ITEM_SPECIFICS_PROMPT_INSTRUCTIONS,
  CATEGORY_PROMPT_INSTRUCTIONS,
  PRODUCT_ANALYSIS_PROMPT_INSTRUCTIONS,
  KEYWORD_PROMPT_INSTRUCTIONS,
} from "./prompts";
import type { NormalizedProductData } from "@/types/product";

/**
 * AI SERVICE — the only place in the app that talks to the OpenAI API.
 * Every function:
 *   1. builds a centralized prompt (see prompts.ts),
 *   2. calls the model requesting strict JSON,
 *   3. validates the response against a zod schema,
 *   4. falls back to a clearly-labeled demo/offline response if no
 *      OPENAI_API_KEY is configured, so the app works without credentials.
 *
 * The API key is read from process.env — this file must only be
 * imported from server-side code (API routes / server components).
 */

function getClient(): OpenAI | null {
  const key = process.env.OPENAI_API_KEY;
  if (!key) return null;
  return new OpenAI({ apiKey: key });
}

async function callModelJSON<T>(prompt: string, schema: z.ZodType<T>, demoFallback: () => T): Promise<T> {
  const client = getClient();
  if (!client) return demoFallback();

  const model = process.env.OPENAI_MODEL || "gpt-4o-mini";
  const completion = await client.chat.completions.create({
    model,
    messages: [
      { role: "system", content: "You are a precise, factual e-commerce listing assistant. Always respond with valid JSON only." },
      { role: "user", content: prompt },
    ],
    response_format: { type: "json_object" },
    temperature: 0.4,
  });

  const raw = completion.choices[0]?.message?.content ?? "{}";
  const parsed = JSON.parse(raw);
  const result = schema.safeParse(parsed);
  if (!result.success) {
    throw new Error(`AI response failed schema validation: ${result.error.message}`);
  }
  return result.data;
}

// ── generateTitle ────────────────────────────────────────────────

const TitleSchema = z.object({
  title: z.string(),
  characterCount: z.number(),
  keywordSuggestions: z.array(z.string()),
  potentialIssues: z.array(z.string()),
});
export type TitleResult = z.infer<typeof TitleSchema>;

export async function generateTitle(product: NormalizedProductData, charLimit = 80): Promise<TitleResult> {
  const prompt = buildPrompt("Generate an optimized eBay title.", product, TITLE_PROMPT_INSTRUCTIONS(charLimit));
  return callModelJSON(prompt, TitleSchema, () => {
    const base = product.title.slice(0, charLimit);
    return {
      title: base,
      characterCount: base.length,
      keywordSuggestions: [],
      potentialIssues: ["Demo Mode: title generated by truncating the source title. Connect an OpenAI API key in Settings → API for AI-optimized titles."],
    };
  });
}

// ── generateDescription ──────────────────────────────────────────

const DescriptionSchema = z.object({ html: z.string() });
export type DescriptionResult = z.infer<typeof DescriptionSchema>;

export async function generateDescription(product: NormalizedProductData): Promise<DescriptionResult> {
  const prompt = buildPrompt("Generate an eBay listing description.", product, DESCRIPTION_PROMPT_INSTRUCTIONS);
  return callModelJSON(prompt, DescriptionSchema, () => ({
    html: demoDescriptionHtml(product),
  }));
}

function demoDescriptionHtml(product: NormalizedProductData): string {
  const specs = product.specifications.length
    ? `<ul>${product.specifications.map((s) => `<li><strong>${escapeHtml(s.key)}:</strong> ${escapeHtml(s.value)}</li>`).join("")}</ul>`
    : "<p>Not specified.</p>";
  const variations = product.variations.length
    ? `<ul>${product.variations.map((v) => `<li>${escapeHtml(v.type)}: ${escapeHtml(v.value)}</li>`).join("")}</ul>`
    : "<p>No variations listed.</p>";

  return `
<h3>PRODUCT OVERVIEW</h3>
<p>${escapeHtml(product.description ?? "Not specified.")}</p>
<h3>KEY FEATURES</h3>
<p>See product specifications below for verified details.</p>
<h3>PRODUCT SPECIFICATIONS</h3>
${specs}
<h3>AVAILABLE VARIATIONS</h3>
${variations}
<h3>PACKAGE CONTENTS</h3>
<p>Not specified — please verify against the source listing before publishing.</p>
<h3>IMPORTANT INFORMATION</h3>
<p>This listing was generated in Demo Mode from source data only. Connect an OpenAI API key in Settings → API for an AI-polished description.</p>
`.trim();
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));
}

// ── generateItemSpecifics ────────────────────────────────────────

const SpecificsSchema = z.object({
  specifics: z.array(z.object({ name: z.string(), value: z.string(), confidence: z.enum(["HIGH", "MEDIUM", "LOW"]) })),
});
export type SpecificsResult = z.infer<typeof SpecificsSchema>;

export async function generateItemSpecifics(product: NormalizedProductData): Promise<SpecificsResult> {
  const prompt = buildPrompt("Map product data to eBay Item Specifics.", product, ITEM_SPECIFICS_PROMPT_INSTRUCTIONS);
  return callModelJSON(prompt, SpecificsSchema, () => ({
    specifics: [
      { name: "Brand", value: product.brand ?? "Not Specified", confidence: product.brand ? "HIGH" : "LOW" },
      { name: "Model", value: product.model ?? "Not Specified", confidence: product.model ? "HIGH" : "LOW" },
      {
        name: "Material",
        value: product.specifications.find((s) => /material/i.test(s.key))?.value ?? "Not Specified",
        confidence: product.specifications.some((s) => /material/i.test(s.key)) ? "HIGH" : "LOW",
      },
      { name: "Color", value: product.variations.find((v) => v.type === "Color")?.value ?? "Not Specified", confidence: "MEDIUM" },
    ],
  }));
}

// ── suggestCategory ──────────────────────────────────────────────

const CategorySchema = z.object({
  recommendedCategory: z.string(),
  alternativeCategories: z.array(z.string()),
  confidence: z.enum(["HIGH", "MEDIUM", "LOW"]),
  reason: z.string(),
});
export type CategoryResult = z.infer<typeof CategorySchema>;

export async function suggestCategory(product: NormalizedProductData): Promise<CategoryResult> {
  const prompt = buildPrompt("Suggest an eBay category.", product, CATEGORY_PROMPT_INSTRUCTIONS);
  return callModelJSON(prompt, CategorySchema, () => ({
    recommendedCategory: "Not specified (Demo Mode)",
    alternativeCategories: [],
    confidence: "LOW" as const,
    reason: "Connect an OpenAI API key in Settings → API to get an AI category suggestion, or set the category manually.",
  }));
}

// ── analyzeProduct ────────────────────────────────────────────────

const AnalysisSchema = z.object({
  whyItMayWork: z.string(),
  advantages: z.array(z.string()),
  risks: z.array(z.string()),
  competitionConcerns: z.string(),
  pricingObservations: z.string(),
  shippingConcerns: z.string(),
  seasonality: z.enum(["evergreen", "seasonal", "trending", "unclear"]),
  targetCustomer: z.string(),
  suggestedKeywords: z.array(z.string()),
  aiCompetitionEstimate: z.number(),
  aiTrendEstimate: z.number(),
  aiSeasonalityEstimate: z.number(),
  aiEbayFitEstimate: z.number(),
});
export type AnalysisResult = z.infer<typeof AnalysisSchema>;

export async function analyzeProduct(product: NormalizedProductData): Promise<AnalysisResult> {
  const prompt = buildPrompt("Analyze this product as a potential eBay resell item.", product, PRODUCT_ANALYSIS_PROMPT_INSTRUCTIONS);
  return callModelJSON(prompt, AnalysisSchema, () => ({
    whyItMayWork: "Demo Mode: qualitative analysis requires an OpenAI API key. Below are neutral placeholder estimates based only on available numeric data.",
    advantages: product.orderCount && product.orderCount > 1000 ? ["High existing order volume on the source listing."] : [],
    risks: ["AI qualitative analysis not available in Demo Mode."],
    competitionConcerns: "Not specified (Demo Mode).",
    pricingObservations: "Not specified (Demo Mode).",
    shippingConcerns: product.shippingCost === 0 ? "Free shipping on source listing." : "Not specified (Demo Mode).",
    seasonality: "unclear" as const,
    targetCustomer: "Not specified (Demo Mode).",
    suggestedKeywords: [],
    aiCompetitionEstimate: 50,
    aiTrendEstimate: 50,
    aiSeasonalityEstimate: 65,
    aiEbayFitEstimate: 55,
  }));
}

// ── generateKeywords ──────────────────────────────────────────────

const KeywordsSchema = z.object({ keywords: z.array(z.object({ keyword: z.string(), relevance: z.number() })) });
export type KeywordsResult = z.infer<typeof KeywordsSchema>;

export async function generateKeywords(product: NormalizedProductData): Promise<KeywordsResult> {
  const prompt = buildPrompt("Suggest eBay search keywords.", product, KEYWORD_PROMPT_INSTRUCTIONS);
  return callModelJSON(prompt, KeywordsSchema, () => ({
    keywords: product.title
      .split(/\s+/)
      .filter((w) => w.length > 3)
      .slice(0, 8)
      .map((w, idx) => ({ keyword: w, relevance: 100 - idx * 8 })),
  }));
}

export function isAiConfigured(): boolean {
  return !!process.env.OPENAI_API_KEY;
}
